### PR TITLE
Single side component board

### PR DESCRIPTION
**Pull request by pilatomic**
Hello,

I have redone the routing of the PCB in order to fit all components on one side of the board. 
( I prefer it that way since it make assembly easier, and the board is more robust since there is no fragile part on the underside ).

I also made some changes, partly to ease routing but also to better fit my use case ( specifically replaced the mini-USB connector by a more common micro-USB one, moving it to the back of the board, and replaced the BOOT0 header with a simple SMD jumper ).

Boards and parts are on their way, I should be able to perform the assembly during next week and check that I did not introduce any issue with the board.

This is not a true pull request yet, more something like a RFC we can discuss these changes.

I think these changes can by useful for other users too, so if you are satisfied with them you are free to merge them once I confirm the board performs as expected.

A big thank you for starting and maintaining this project !
Regards

### CODE REVIEW

**Comment by bbogush** [comment]
Hello,
Thank you for great work. Singe side components board makes sense. Previously I used differential pair for USB_P USB_N connections but for full speed USB current difference in wire length in ~1mm is ok. New quartz and USB are ok. Though these components come in different flavours and there may be problem to find the same ones. It would be nice if you provide datasheet link for them.
Regards

**Comment by pilatomic** [comment]
Hello,

Indeed, I did not try to length-match the USB tracks due to the relative low speed of the signals, but maybe I should do it, what do you think ?

Regarding the components, the USB connector can be identified by its footprint in Kicad, which contains the exact model. Still, I will add the exact model number.

I can also provide Farnell numbers for each component ( except for the SWD and UART headers, the headers I bought are too tall, I need to find another part number ).

I just finished assembly, flashed the firmware, and tested with your software, it appears to work fine.I have only tested that your software can communicate with the board, as I am still waiting for my TSOP48 adapter to be delivered. I hope it won't be long. But it at least proves that the quartz is fine.

I also just made a slight change, the PWR led footprint direction was swapped, since previously I had it in the other direction than the other leds, and I caught me during assembly.

I might also need to find another part number for the leds or change the associated resistors, since at least the PWR led appears very dim.

Here is a picture of the PCB assembled
Nando_Pila

I will keep you updated when I receive my TSOP48 adapter and fully test the functionality.

Regards

**Comment by bbogush** [comment]
Hello,
The board looks nice. 
I think no need to adjust usb tracks, length difference is in acceptable range and it is hard to route with kicad differential pair tool there.
I am going to make list of parts with links to some international website where they can be ordered so Farnell numbers can be useful.
I look forward for updates.
Regards

**Comment by pilatomic** [comment]
Hello,

I will keep you updated as soon as my TSOP adapter is delivered (can't wait for this, since I actually need to edit some flash content). 
Regarding the Farnell numbers, I will rebuild the list from my Farnell invoice.

I forgot to mention in my previous message, but while soldering the resistors, one thing got me puzzled : the values of the R1 and R15 resistors. R15 ties BOOT0 to GND quite strongly. 
I think you put R1 to protect the 3.3V line, but with a 10k value, it will never be able to win against R15 to pull BOOT0 strong enough to 3.3V.
Should R1 and R15 be swapped ( it seems it would make more sense pulling BOOT0 to GND through 10k ? ).

Regards

**Comment by bbogush** [comment]
Hello, 
You are right, the values of R1 and R15 are wrong and should be swapped. Thanks for noticing.
Regards

**Comment by pilatomic** [comment]
Hello,

I corrected the R1/R15 issue.
My TSOP adapter was finally delivered, so I got to really try some nand read / write.
It seems I swapped the RD and WR leds during routing, that's corrected now.

Reading the nand seems to work, but i'm having some issue where writing / erasing does not work
I need to double check the timing for my nand chip ( HY27US08121B ), but it should be basically identical to the HY27US08561A that is already present in the chip database.

Regarding the Farnell order codes, how do you want to proceed ? 
I usually store them in the schematic, as another property of each component, that allows me to benefit from Kicad BOM generator including tthem in the BOM.
Are you satisfied with the approach ?

signal-2020-06-18-155926

Regards

**Comment by bbogush** [comment]
Hello,
Glad to hear writing of NAND works. 
Including Farnell order codes as  property of each component is ok for me. I think having them in BOM is very useful. Thank you for idea.

Regards

**Comment by pilatomic** [comment]
Hello,

I've updated the schematic file with all the farnell refs, so I think this is finally getting ready for a merge !
I'll also open another merge request for the updated chip database ( with the added specs for the nand chip I edited ).

Regards

**Comment by bbogush** [comment]
Hello,

Thank you for contribution!

Regards

**Pull request merged**
