### PR TITLE
Feature/add macos support

### PR DESCRIPTION
**Pull request by liqili**
Add MacOS host app support
Add CMAKE build support
Fix some issues

### CODE REVIEW

**Comment by bbogush** [comment]
Thanks for pull request. 
It has some build issues due to compiler path variable change
`
make[5]: Entering directory '/data/dev/nand_programmer/firmware/libs/spl'
mkdir -p obj/
../../compiler/gcc-arm-none-eabi-4_9-2015q1/bin/arm-none-eabi-gcc -c -g -Wall -Werror -Og   -ffunction-sections -fdata-sections -MMD -MP -mcpu=cortex-m3 -mthumb -DSTM32F10X_HD -DCONFIG_BOOTLOADER -includestm32f10x_conf.h -I. -ISTM32F10x_StdPeriph_Driver/inc/ -ISTM32_USB-FS-Device_Driver/inc/ -ICMSIS/CM3/DeviceSupport/ST/STM32F10x/ -ICMSIS/CM3/CoreSupport/ -ffreestanding -nostdlib -includestm32f10x_conf.h -I. -ISTM32F10x_StdPeriph_Driver/inc/ -ISTM32_USB-FS-Device_Driver/inc/ -ICMSIS/CM3/DeviceSupport/ST/STM32F10x/ -ICMSIS/CM3/CoreSupport/ startup_stm32f10x_hd.s -o obj/startup_stm32f10x_hd.o
make[5]: ../../compiler/gcc-arm-none-eabi-4_9-2015q1/bin/arm-none-eabi-gcc: No such file or directory
`

**Comment by liqili** [comment]
Compilation issue fixed.

**Comment by bbogush** [comment]
Great work. Thank you!

**Comment by banoz** [comment]
This commit completely wrecked FW build on Windows btw

**Comment by bbogush** [comment]
Unfortunately reverted due to build issue on Windows

**Pull request merged**
